[package]
name = "merge-tool"
version = "0.1.2"
edition = "2024"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
], default-features = false }
reqwest = { version = "0.12.15", features = [
    "json",
    "default-tls",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui = "0.29"
crossterm = "0.28.1"
chrono = "0.4"
anyhow = "1.0"
base64 = "0.22.1"
clap = { version = "4.0", features = ["derive"] }
async-trait = "0.1.88"
tempfile = "3.20"
scraper = "0.23.1"
ego-tree = "0.10.0"
toml = "0.8"
dirs = "5.0"
regex = "1.10"

[dev-dependencies]
mockito = "1.7"
tokio-test = "0.4"
tempfile = "3.23"
